version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=kinesis,dynamodb
      - START_WEB=0
      - DEFAULT_REGION=eu-central-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack:/tmp/localstack'

  wait-localstack:
    image: alpine:latest
    depends_on:
      - localstack
    command: >
      /bin/sh -c '
      apk add --no-cache curl
      until curl -sS http://localstack:4566/health | grep "\"services\": {"; do sleep 1; done
      '

networks:
  default:
    name: localstack-network
