service: product-service

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

functions:
  product-service:
    handler: app.handler
    environment:
      STREAM_NAME: my-stream
      STREAM_ARN: arn:aws:kinesis:eu-central-1:000000000000:stream/my-stream
      REGION: eu-central-1
      ENDPOINT: http://localhost:4566
      TABLE_NAME: product-table

resources:
  Resources:
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: product-table
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3007
    lambdaPort: 3008
